// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKtmVnuj8HPtK_G1HKOXGYCYA9j7oP0Yk',
    appId: '1:1054782259941:web:f1fd7a5fcd9881ae370a0c',
    messagingSenderId: '1054782259941',
    projectId: 'barakatrans-4e936',
    authDomain: 'barakatrans-4e936.firebaseapp.com',
    databaseURL: 'https://barakatrans-4e936-default-rtdb.firebaseio.com',
    storageBucket: 'barakatrans-4e936.appspot.com',
    measurementId: 'G-QNWHQNB96B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDETjfsuX1VIc8j_74CnXfchZb5g2cS12E',
    appId: '1:1054782259941:android:8a65729583001b70370a0c',
    messagingSenderId: '1054782259941',
    projectId: 'barakatrans-4e936',
    databaseURL: 'https://barakatrans-4e936-default-rtdb.firebaseio.com',
    storageBucket: 'barakatrans-4e936.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3QiMVytECsIjQ1dAonuCs7tXTuxpc8gE',
    appId: '1:1054782259941:ios:af49e18d82ca73c1370a0c',
    messagingSenderId: '1054782259941',
    projectId: 'barakatrans-4e936',
    databaseURL: 'https://barakatrans-4e936-default-rtdb.firebaseio.com',
    storageBucket: 'barakatrans-4e936.appspot.com',
    iosBundleId: 'com.barakatrans.barakaTrans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3QiMVytECsIjQ1dAonuCs7tXTuxpc8gE',
    appId: '1:1054782259941:ios:af49e18d82ca73c1370a0c',
    messagingSenderId: '1054782259941',
    projectId: 'barakatrans-4e936',
    databaseURL: 'https://barakatrans-4e936-default-rtdb.firebaseio.com',
    storageBucket: 'barakatrans-4e936.appspot.com',
    iosBundleId: 'com.barakatrans.barakaTrans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKtmVnuj8HPtK_G1HKOXGYCYA9j7oP0Yk',
    appId: '1:1054782259941:web:459224b2a6fc5fe3370a0c',
    messagingSenderId: '1054782259941',
    projectId: 'barakatrans-4e936',
    authDomain: 'barakatrans-4e936.firebaseapp.com',
    databaseURL: 'https://barakatrans-4e936-default-rtdb.firebaseio.com',
    storageBucket: 'barakatrans-4e936.appspot.com',
    measurementId: 'G-VK1LYYR0V6',
  );
}
